name: Update README with GitHub stats

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README with GitHub stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install required packages
        run: npm install -g github-stats-card

      - name: Update README with GitHub stats
        run: github-stats-card --username rinoscronauta --theme default --cache --output README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with GitHub stats"
          git push
