name: Update README with recent activity

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JQ
        run: sudo apt-get install jq

      - name: Fetch recent activity
        id: fetch_activity
        uses: octokit/request-action@v2.x
        with:
          route: GET /users/:username/events
          username: rinoscronauta
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Update README
        run: |
          recent_activity=$(echo '${{ steps.fetch_activity.outputs.data }}' | jq -r '.[] | "- \(.type) at [\(.repo.name)](https://github.com/\(.repo.name))"')
          readme=$(cat README.md)
          new_readme=$(echo "$readme" | sed -e "/<!--START_SECTION:activity-->/, /<!--END_SECTION:activity-->/c\\
<!--START_SECTION:activity-->\\
$recent_activity\\
<!--END_SECTION:activity-->")
          echo "$new_readme" > README.md
          git config --global user.email "youremail@example.com"
          git config --global user.name "rinoscronauta"
          git add README.md
          git commit -m "Update recent activity"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
