name: Update README with recent activity

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1.2.0
        with:
          feed_list: "https://github.com/yourusername.private.atom?token=YOUR_TOKEN"
          readme_path: "README.md"
          gh_token: ${{ secrets.GH_TOKEN }}
